// <auto-generated />
using System;
using Graduation_Project.Repository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Graduation_Project.Repository.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250225204159_LangauageMigration")]
    partial class LangauageMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Graduation_Project.Core.Models.Clinics.ClincSecretary", b =>
                {
                    b.Property<int>("ClincId")
                        .HasColumnType("int");

                    b.Property<int>("SecretaryId")
                        .HasColumnType("int");

                    b.HasKey("ClincId", "SecretaryId");

                    b.HasIndex("SecretaryId");

                    b.ToTable("clincSecretaries");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Clinics.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("clinics");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Clinics.ContactNumber", b =>
                {
                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ClinicId", "PhoneNumber");

                    b.ToTable("contactNumbers");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Clinics.Governorate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name_ar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_en")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("governorates");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Clinics.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name_ar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_en")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("governorateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("governorateId");

                    b.ToTable("regions");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Clinics.Secretary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalID")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("secretaries");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Clinics.TherapySession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SessionTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("clinicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("clinicId");

                    b.ToTable("therapySessions");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Doctors.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ConsultationFees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ExperianceYears")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MedicalLicensePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalID")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<int?>("SecretaryId")
                        .HasColumnType("int");

                    b.Property<int?>("SpecialtyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SecretaryId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Doctors.DoctorClinic", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DoctorId", "ClinicId");

                    b.HasIndex("ClinicId");

                    b.ToTable("DoctorClinics");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Doctors.DoctorSubspeciality", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("SubSpecialitiesId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("DoctorId", "SubSpecialitiesId");

                    b.HasIndex("SubSpecialitiesId");

                    b.ToTable("DoctorSubspecialities");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Doctors.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Certifications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Degree")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Fellowships")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId")
                        .IsUnique();

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Doctors.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Specialties");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Doctors.SubSpecialities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("SubSpecialities");

                    b.HasAnnotation("Relational:JsonPropertyName", "SubSpecialties");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Notifications.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Notifications.NotificationRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("NotificationId")
                        .HasColumnType("int");

                    b.Property<int>("RecipientType")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("patientId")
                        .HasColumnType("int");

                    b.Property<int>("pharmacistId")
                        .HasColumnType("int");

                    b.Property<int>("secretaryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("NotificationId");

                    b.HasIndex("patientId");

                    b.HasIndex("pharmacistId");

                    b.HasIndex("secretaryId");

                    b.ToTable("notificationRecipients");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Patients.AI_QuickDiagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Recommendations")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("AI_QuickDiagnoses");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Patients.MedicalCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("MedicalCategories");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Patients.MedicalHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MedicalCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("MedicalImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicalCategoryId");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalHistories");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Patients.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BloodType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Points")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Patients.RadiologyReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AIAnalysis")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("RadiologyReports");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Pharmacies.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveSubstance")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DosageForm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Pharmacies.MedicinePharmacy", b =>
                {
                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("MedicineId", "PharmacyId");

                    b.ToTable("MedicinePharmacies");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Pharmacies.MedicinePharmacyOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("PharmacyOrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PharmacyOrderId");

                    b.ToTable("MedicinePharmacyOrders");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Pharmacies.Pharmacist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalID")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("PharmacistLicensePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pharmacists");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Pharmacies.Pharmacy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longtude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PharmacistId")
                        .HasColumnType("int");

                    b.Property<string>("PharmacyLicensePictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PharmacistId");

                    b.ToTable("Pharmacies");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Pharmacies.PharmacyOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("int");

                    b.Property<string>("PrescriptionPictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("PharmacyId");

                    b.ToTable("PharmacyOrders");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Shared.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("VideoLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Shared.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Favorite");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Shared.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Shared.MedicinePrescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("MedicinePrescription");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Shared.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Diagnoses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Prescription");
                });

            modelBuilder.Entity("MedicineMedicinePharmacy", b =>
                {
                    b.Property<int>("MedicinesId")
                        .HasColumnType("int");

                    b.Property<int>("MedicinePharmaciesMedicineId")
                        .HasColumnType("int");

                    b.Property<int>("MedicinePharmaciesPharmacyId")
                        .HasColumnType("int");

                    b.HasKey("MedicinesId", "MedicinePharmaciesMedicineId", "MedicinePharmaciesPharmacyId");

                    b.HasIndex("MedicinePharmaciesMedicineId", "MedicinePharmaciesPharmacyId");

                    b.ToTable("MedicineMedicinePharmacy");
                });

            modelBuilder.Entity("MedicinePharmacyPharmacy", b =>
                {
                    b.Property<int>("PharmaciesId")
                        .HasColumnType("int");

                    b.Property<int>("MedicinePharmaciesMedicineId")
                        .HasColumnType("int");

                    b.Property<int>("MedicinePharmaciesPharmacyId")
                        .HasColumnType("int");

                    b.HasKey("PharmaciesId", "MedicinePharmaciesMedicineId", "MedicinePharmaciesPharmacyId");

                    b.HasIndex("MedicinePharmaciesMedicineId", "MedicinePharmaciesPharmacyId");

                    b.ToTable("MedicinePharmacyPharmacy");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Clinics.ClincSecretary", b =>
                {
                    b.HasOne("Graduation_Project.Core.Models.Clinics.Clinic", "clinic")
                        .WithMany("clincSecretarys")
                        .HasForeignKey("ClincId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Graduation_Project.Core.Models.Clinics.Secretary", "secretary")
                        .WithMany("clincSecretarys")
                        .HasForeignKey("SecretaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("clinic");

                    b.Navigation("secretary");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Clinics.Clinic", b =>
                {
                    b.HasOne("Graduation_Project.Core.Models.Clinics.Region", "Region")
                        .WithMany("clinics")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Clinics.ContactNumber", b =>
                {
                    b.HasOne("Graduation_Project.Core.Models.Clinics.Clinic", "clinic")
                        .WithMany("ContactNumbers")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("clinic");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Clinics.Region", b =>
                {
                    b.HasOne("Graduation_Project.Core.Models.Clinics.Governorate", "governorate")
                        .WithMany("regions")
                        .HasForeignKey("governorateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("governorate");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Clinics.TherapySession", b =>
                {
                    b.HasOne("Graduation_Project.Core.Models.Doctors.Doctor", "Doctor")
                        .WithMany("TherapySessions")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Graduation_Project.Core.Models.Patients.Patient", "Patient")
                        .WithMany("TherapySessions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Graduation_Project.Core.Models.Clinics.Clinic", "clinic")
                        .WithMany("therapySessions")
                        .HasForeignKey("clinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("clinic");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Doctors.Doctor", b =>
                {
                    b.HasOne("Graduation_Project.Core.Models.Clinics.Secretary", null)
                        .WithMany("doctors")
                        .HasForeignKey("SecretaryId");

                    b.HasOne("Graduation_Project.Core.Models.Doctors.Specialty", "Specialty")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecialtyId");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Doctors.DoctorClinic", b =>
                {
                    b.HasOne("Graduation_Project.Core.Models.Clinics.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Graduation_Project.Core.Models.Doctors.Doctor", "Doctor")
                        .WithMany("DoctorClincs")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Doctors.DoctorSubspeciality", b =>
                {
                    b.HasOne("Graduation_Project.Core.Models.Doctors.Doctor", "Doctor")
                        .WithMany("DoctorSubspeciality")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Graduation_Project.Core.Models.Doctors.SubSpecialities", "SubSpecialities")
                        .WithMany("DoctorSubspeciality")
                        .HasForeignKey("SubSpecialitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("SubSpecialities");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Doctors.Education", b =>
                {
                    b.HasOne("Graduation_Project.Core.Models.Doctors.Doctor", "Doctor")
                        .WithOne("Education")
                        .HasForeignKey("Graduation_Project.Core.Models.Doctors.Education", "DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Doctors.SubSpecialities", b =>
                {
                    b.HasOne("Graduation_Project.Core.Models.Doctors.Specialty", "Specialty")
                        .WithMany("SubSpecialities")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Notifications.NotificationRecipient", b =>
                {
                    b.HasOne("Graduation_Project.Core.Models.Doctors.Doctor", "Doctor")
                        .WithMany("NotificationRecipients")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Graduation_Project.Core.Models.Notifications.Notification", "Notification")
                        .WithMany("Recipients")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Graduation_Project.Core.Models.Patients.Patient", "patient")
                        .WithMany("NotificationRecipients")
                        .HasForeignKey("patientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Graduation_Project.Core.Models.Pharmacies.Pharmacist", "pharmacist")
                        .WithMany("NotificationRecipients")
                        .HasForeignKey("pharmacistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Graduation_Project.Core.Models.Clinics.Secretary", "secretary")
                        .WithMany("notificationRecipients")
                        .HasForeignKey("secretaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Notification");

                    b.Navigation("patient");

                    b.Navigation("pharmacist");

                    b.Navigation("secretary");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Patients.AI_QuickDiagnosis", b =>
                {
                    b.HasOne("Graduation_Project.Core.Models.Patients.Patient", "Patient")
                        .WithMany("AIQuickDiagnosis")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Patients.MedicalHistory", b =>
                {
                    b.HasOne("Graduation_Project.Core.Models.Patients.MedicalCategory", "MedicalCategory")
                        .WithMany("MedicalHistories")
                        .HasForeignKey("MedicalCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Graduation_Project.Core.Models.Patients.Patient", "Patient")
                        .WithMany("MedicalHistories")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalCategory");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Patients.RadiologyReport", b =>
                {
                    b.HasOne("Graduation_Project.Core.Models.Patients.Patient", "Patient")
                        .WithMany("RadiologyReports")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Pharmacies.MedicinePharmacyOrder", b =>
                {
                    b.HasOne("Graduation_Project.Core.Models.Pharmacies.Medicine", "Medicine")
                        .WithMany("MedicinePharmacyOrders")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Graduation_Project.Core.Models.Pharmacies.PharmacyOrder", "PharmacyOrder")
                        .WithMany("MedicinePharmacyOrders")
                        .HasForeignKey("PharmacyOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("PharmacyOrder");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Pharmacies.Pharmacy", b =>
                {
                    b.HasOne("Graduation_Project.Core.Models.Pharmacies.Pharmacist", "Pharmacist")
                        .WithMany("Pharmacies")
                        .HasForeignKey("PharmacistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacist");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Pharmacies.PharmacyOrder", b =>
                {
                    b.HasOne("Graduation_Project.Core.Models.Patients.Patient", "Patient")
                        .WithMany("PharmacyOrder")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Graduation_Project.Core.Models.Pharmacies.Pharmacy", "Pharmacy")
                        .WithMany("PharmacyOrders")
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Shared.Appointment", b =>
                {
                    b.HasOne("Graduation_Project.Core.Models.Clinics.Clinic", "Clinic")
                        .WithMany("Appointments")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Graduation_Project.Core.Models.Doctors.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Graduation_Project.Core.Models.Patients.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Shared.Favorite", b =>
                {
                    b.HasOne("Graduation_Project.Core.Models.Doctors.Doctor", "Doctor")
                        .WithMany("Favorites")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Graduation_Project.Core.Models.Patients.Patient", "Patient")
                        .WithMany("Favorites")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Shared.Feedback", b =>
                {
                    b.HasOne("Graduation_Project.Core.Models.Doctors.Doctor", "Doctor")
                        .WithMany("Feedbacks")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Graduation_Project.Core.Models.Patients.Patient", "patient")
                        .WithMany("Feedbacks")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Shared.MedicinePrescription", b =>
                {
                    b.HasOne("Graduation_Project.Core.Models.Pharmacies.Medicine", "Medicine")
                        .WithMany("MedicinePrescriptions")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Graduation_Project.Core.Models.Shared.Prescription", "Prescription")
                        .WithMany("MedicinePrescriptions")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Shared.Prescription", b =>
                {
                    b.HasOne("Graduation_Project.Core.Models.Doctors.Doctor", "Doctor")
                        .WithMany("Prescriptions")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Graduation_Project.Core.Models.Patients.Patient", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MedicineMedicinePharmacy", b =>
                {
                    b.HasOne("Graduation_Project.Core.Models.Pharmacies.Medicine", null)
                        .WithMany()
                        .HasForeignKey("MedicinesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Graduation_Project.Core.Models.Pharmacies.MedicinePharmacy", null)
                        .WithMany()
                        .HasForeignKey("MedicinePharmaciesMedicineId", "MedicinePharmaciesPharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicinePharmacyPharmacy", b =>
                {
                    b.HasOne("Graduation_Project.Core.Models.Pharmacies.Pharmacy", null)
                        .WithMany()
                        .HasForeignKey("PharmaciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Graduation_Project.Core.Models.Pharmacies.MedicinePharmacy", null)
                        .WithMany()
                        .HasForeignKey("MedicinePharmaciesMedicineId", "MedicinePharmaciesPharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Clinics.Clinic", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ContactNumbers");

                    b.Navigation("clincSecretarys");

                    b.Navigation("therapySessions");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Clinics.Governorate", b =>
                {
                    b.Navigation("regions");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Clinics.Region", b =>
                {
                    b.Navigation("clinics");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Clinics.Secretary", b =>
                {
                    b.Navigation("clincSecretarys");

                    b.Navigation("doctors");

                    b.Navigation("notificationRecipients");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Doctors.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DoctorClincs");

                    b.Navigation("DoctorSubspeciality");

                    b.Navigation("Education")
                        .IsRequired();

                    b.Navigation("Favorites");

                    b.Navigation("Feedbacks");

                    b.Navigation("NotificationRecipients");

                    b.Navigation("Prescriptions");

                    b.Navigation("TherapySessions");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Doctors.Specialty", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("SubSpecialities");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Doctors.SubSpecialities", b =>
                {
                    b.Navigation("DoctorSubspeciality");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Notifications.Notification", b =>
                {
                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Patients.MedicalCategory", b =>
                {
                    b.Navigation("MedicalHistories");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Patients.Patient", b =>
                {
                    b.Navigation("AIQuickDiagnosis");

                    b.Navigation("Appointments");

                    b.Navigation("Favorites");

                    b.Navigation("Feedbacks");

                    b.Navigation("MedicalHistories");

                    b.Navigation("NotificationRecipients");

                    b.Navigation("PharmacyOrder");

                    b.Navigation("Prescriptions");

                    b.Navigation("RadiologyReports");

                    b.Navigation("TherapySessions");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Pharmacies.Medicine", b =>
                {
                    b.Navigation("MedicinePharmacyOrders");

                    b.Navigation("MedicinePrescriptions");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Pharmacies.Pharmacist", b =>
                {
                    b.Navigation("NotificationRecipients");

                    b.Navigation("Pharmacies");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Pharmacies.Pharmacy", b =>
                {
                    b.Navigation("PharmacyOrders");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Pharmacies.PharmacyOrder", b =>
                {
                    b.Navigation("MedicinePharmacyOrders");
                });

            modelBuilder.Entity("Graduation_Project.Core.Models.Shared.Prescription", b =>
                {
                    b.Navigation("MedicinePrescriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
